### ISSUE TITLE
NuGet?

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#52]
Hi,

are you interested in publishing dnlib as a NuGet package?
There are ways to trigger automatic build and publishing to NuGet, using appveyor, for example.
I use this a lot for my projects and it just eases the release life cycle.
If you are interested you need to:
- register to NuGet and Appveyor (this latter uses Github for login)
- add a .nuspec file to the project (I'll provide a sample later... If you are interested).
- add a file named `appveyor.yml` to your project (I provide a sample content below)
- add the project to appveyor (register it, actually, this step is very easy since appveyor will fetch your GitHub projects).
- of course use your own key (see after sample for details)

```
# appveyor.yml script

version: '{branch}-{build}'

branches:
  only:
    - master

os: Visual Studio 2015
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true   
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: !!!place your own API key here!!!
  skip_symbols: false
```
The API key you need to provide is the NuGet key encrypted by appveyor (so appveyor is the only one allowed to decipher it).
I would gladly have submitted a push request, however it would have contained my own NuGet key, and this is your great product, not mine :smile: .
